config/routes.rb
Rails.application.routes.draw do
  get 'sign_up' => "users#new", :as => "sign_up"
  get 'login' => "sessions#new", :as => "login"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get '/users/confirm_email/:confirm_token' => 'users#confirm_email', as: 'confirm'
  get 'welcome/index'
  get 'welcome/about'
  
  resources :users
  resources :sessions
  resources :password_resets
  root to: 'welcome#about'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  before_create :confirmation_token

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def email_activate!
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end
  
  private
  
  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  
  private 
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => "Email sent with password reset instructions."
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(params.require(:user).permit(:password, :password_confirmation))
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit, :error => "Something went wrong. Please try again."
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate!, only: [:new, :create]
  
  def new
  end
  
  # handles authentications when a user submits login form
  def create
    user = User.authenticate(params[:email], params[:password])
    
    if user
      session[:user_id] = user.id
      flash[:notice] = "Logged in!"
      redirect_to root_url
    else
      flash.now.alert = "Invalid email or password"
      render :new
    end
  end
  
  # removes logged user.id from session
  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate!, only: [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      UserMailer.signup_confirmation(@user).deliver_now!
      flash[:notice] = "You've signed up successfully! Please look for a confirmation email shortly."
      redirect_to root_path
    else
      flash[:error] = "Something went wrong, please try again."
      render :new
    end
  end
  
  def confirm_email
    user = User.find_by_confirm_token(params[:confirm_token])
    if user
      user.email_activate!
      flash[:notice] = "Your email has been confirmed #{@user}! Please sign in to continue."
      redirect_to login_path
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_path
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password, :salt, :encrypted_password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
      </div>
      <div class="pull-right user-info">
        <% if current_user %>
          <p>Hello <%= link_to current_user.email %>! <small><%= link_to "Log Out", log_out_path %> or <%= link_to "Reset Password", new_password_reset_path %></small></p>
        <% else %>
         <p>
           <%= link_to "Sign In", login_path %> or
           <%= link_to "Sign Up", sign_up_path %>
         </p>
        <% end %>
      </div>
    </div>
    <div class="row">
      <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
    </div>
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Password Reset</h1>
<p>
  Fill out the form below to reset your password
</p>
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <p>
      <%= f.label :password %>
      <br/>
      <%= f.password_field :password %>
    </p>
  </div>
  <div class="field">
    <p>
      <%= f.label :password_confirmation %>
      <br/>
      <%= f.password_field :password_confirmation %>
    </p>
  </div>
  <p class="button">
    <%= submit_tag "Update Password" %>
  </p>
<% end %>

app/views/password_resets/new.html.erb
<h1>Password Reset</h1>
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <p>
      <%= label_tag :email %>
      <br/>
      <%= text_field_tag :email, params[:email] %>
    </p>
  </div>
  <div class="actions"></div>
  <p class="button">
    <%= submit_tag "Reset Password" %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>Welcome to Blocmetrics! Please enter a valid email and password below.</p>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
        <h3>Form is invalid, please check error message.</h3>
        <ul>
            <% for message in @user.errors.full_messages %>
               <li><%= message %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/welcome/about.html.erb
<h1>Blocmetrics</h1>
<p>Welcome to Blocmetrics, an analytics service to track events on websites.</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>